#!/usr/bin/env -S Rscript --vanilla
# encoding: utf-8

#	Copyright (c) 2014-2016, Peder Axensten, all rights reserved.
#	Contact: peder ( at ) axensten.se



	library( stats )
	library( e1071 )
	library( TLMoments )
	
	
	filter <- 0


	data <- c( 1909.0, 1955.0, 1789.0, 1773.0, 2515.0, 2727.0, 2524.0, 2105.0, 2165.0, 2092.0, 2261.0, 1571.0, 2204.0, 2260.0, 2425.0 )
	data <-							data[ data >= filter ]
	dump <- function( id, value )	{	cat( "\t\tstatic constexpr value_type\t\t", id, "{ ", value, " };\n", sep="" )	}
	options( digits=16 )

	n    <-							length( data )
	datamean	<-					mean( data )
	m2   <-							sum( ( data - datamean )^2 )
	m3   <-							sum( ( data - datamean )^3 )
	m4   <-							sum( ( data - datamean )^4 )
	population_variance <-			m2 / ( n )
	sample_variance <-				m2 / ( n - 1 )


	cat( "// Automatically generated by script _metrics-key.r\n\n" )
	cat( "#include <cstddef>\n\n\n" )
	cat( "namespace pax {\n" )
	cat( "\tstruct Correct {\n" )
	cat( "\t\tusing value_type\t\t\t  = double;\n\n" )
	cat( "\t\tstatic constexpr std::size_t\tcount{ 15 };\n" )
	cat( "\t\tstatic constexpr value_type\t\tdataset[ count ]\n\t\t\t{", paste( data, collapse=", " ), "};\n\n" )

	cat( "\n\t\t// Summary:\n" )
	dump( "sum",					sum( data ) )
	dump( "sum2",					sum( data^2 ) )
	dump( "sum3",					sum( data^3 ) )
	dump( "sum4",					sum( data^4 ) )
	dump( "moment0",				e1071::moment( data, center=F, order=0 ) )
	dump( "moment1",				e1071::moment( data, center=F, order=1 ) )
	dump( "moment2",				e1071::moment( data, center=F, order=2 ) )
	dump( "moment3",				e1071::moment( data, center=F, order=3 ) )
	dump( "moment4",				e1071::moment( data, center=F, order=4 ) )
	dump( "moment5",				e1071::moment( data, center=F, order=5 ) )
	dump( "cmoment0",				e1071::moment( data, center=T,  order=0 ) )
	dump( "cmoment1",				e1071::moment( data, center=T,  order=1 ) )
	dump( "cmoment2",				e1071::moment( data, center=T,  order=2 ) )
	dump( "cmoment3",				e1071::moment( data, center=T,  order=3 ) )
	dump( "cmoment4",				e1071::moment( data, center=T,  order=4 ) )
	dump( "cmoment5",				e1071::moment( data, center=T,  order=5 ) )


	dump( "mean",					mean( data ) )
	dump( "population_std_dev",		sqrt( population_variance ) )
	dump( "sample_std_dev",			sqrt( sample_variance ) )
	dump( "population_variance",	population_variance )
	dump( "sample_variance",		sample_variance )
	dump( "coeff_of_sample_var",	sample_variance/mean( data ) )

	dump( "population_skewness",	m3 / ( n*( sqrt( population_variance ) )^3 ) )
	dump( "sample_skewness",		m3*n / ( ( n-1 )*( n-2 )*( sqrt( sample_variance ) )^3 ) )
	dump( "skewness_g1",			e1071::skewness( data, type=1 ) )
	dump( "skewness_G1",			e1071::skewness( data, type=2 ) )
	dump( "skewness_b1",			e1071::skewness( data, type=3 ) )

	kurtosis  <- m4 / ( (n-1)*(n-2)*(n-3)*sample_variance^2 )
	dump( "sample_kurtosis_pearson",	kurtosis*n*( n+1 ) )
	dump( "sample_kurtosis_fisherK",	kurtosis*n*( n+1 )         - 3*n*n        /(       (n-2)*(n-3) ) )
	dump( "sample_kurtosis_fisherM",	kurtosis*( n*n - 2*n + 3 ) - 3*n*( 2*n-3 )/( (n-1)*(n-2)*(n-3) ) )

	dump( "population_kurtosis_pearson",m4/( n * population_variance^2 ) )
	dump( "population_kurtosis_fisher",	e1071::kurtosis( data, type=1 ) )
	dump( "kurtosis_G2",				e1071::kurtosis( data, type=2 ) )
	dump( "kurtosis_b2",				e1071::kurtosis( data, type=3 ) )


	cat( "\n\t\t// Order:\n" )
	dump( "minimum",			min( data ) )
	dump( "quartile1",			quantile( data, probs=0.25 ) )
	dump( "median",				quantile( data, probs=0.50 ) )
	dump( "quartile3",			quantile( data, probs=0.75 ) )
	dump( "maximum",			max( data ) )
	
	dump( "mad",				stats::mad( data, constant = 1.0 ) )
	
	dump( "L1",					TLMoments::TLMoment( data, order=1 ) )
	dump( "L2",					TLMoments::TLMoment( data, order=2 ) )
	dump( "L3",					TLMoments::TLMoment( data, order=3 ) )
	dump( "L4",					TLMoments::TLMoment( data, order=4 ) )
	dump( "L5",					TLMoments::TLMoment( data, order=5 ) )
	dump( "L9",					TLMoments::TLMoment( data, order=9 ) )

	L_ratio <- TLMoments::TLMoments( data, order=1 )$ratios
	dump( "L2_ratio",			L_ratio[ 2 ] )
	dump( "L3_ratio",			L_ratio[ 3 ] )
	dump( "L4_ratio",			L_ratio[ 4 ] )
	
	dump( "TL1",				TLMoments::TLMoment( data, order=1 ) )
	dump( "TL2",				TLMoments::TLMoment( data, order=2 ) )
	dump( "TL3",				TLMoments::TLMoment( data, order=3 ) )
	dump( "TL4",				TLMoments::TLMoment( data, order=4 ) )
	dump( "TL5",				TLMoments::TLMoment( data, order=5 ) )
	dump( "TL9",				TLMoments::TLMoment( data, order=9 ) )
	
	dump( "TL1_1",				TLMoments::TLMoment( data, order=1, leftrim=1, rightrim=1 ) )
	dump( "TL2_1",				TLMoments::TLMoment( data, order=2, leftrim=1, rightrim=1 ) )
	dump( "TL3_1",				TLMoments::TLMoment( data, order=3, leftrim=1, rightrim=1 ) )
	dump( "TL4_1",				TLMoments::TLMoment( data, order=4, leftrim=1, rightrim=1 ) )
	dump( "TL5_1",				TLMoments::TLMoment( data, order=5, leftrim=1, rightrim=1 ) )
	dump( "TL9_1",				TLMoments::TLMoment( data, order=9, leftrim=1, rightrim=1 ) )
	
	dump( "TL1_3_5",			TLMoments::TLMoment( data, order=1, leftrim=3, rightrim=5 ) )
	dump( "TL2_3_5",			TLMoments::TLMoment( data, order=2, leftrim=3, rightrim=5 ) )
	dump( "TL3_3_5",			TLMoments::TLMoment( data, order=3, leftrim=3, rightrim=5 ) )
	dump( "TL4_3_5",			TLMoments::TLMoment( data, order=4, leftrim=3, rightrim=5 ) )
	dump( "TL5_3_5",			TLMoments::TLMoment( data, order=5, leftrim=3, rightrim=5 ) )

	TL_3_5_ratio <- TLMoments::TLMoments( data, order=1, leftrim=3, rightrim=5 )$ratios
	dump( "TL2_3_5_ratio",		TL_3_5_ratio[ 2 ] )
	dump( "TL3_3_5_ratio",		TL_3_5_ratio[ 3 ] )
	dump( "TL4_3_5_ratio",		TL_3_5_ratio[ 4 ] )

	cat( "\n\t};\t// struct Correct\n" )
	cat( "}\t\t// namespace pax\n" )
