// Automatically generated by script _metrics-key.r


#pragma once

#include <cstddef>


namespace pax::metrics {
	struct Correct {
		using value_type			  = double;

		static constexpr std::size_t	count{ 15 };
		static constexpr value_type		dataset[ count ]
			{ 1909, 1955, 1789, 1773, 2515, 2727, 2524, 2105, 2165, 2092, 2261, 1571, 2204, 2260, 2425 };


		// Summary:
		static constexpr value_type		sum{ 32275 };
		static constexpr value_type		sum2{ 70863403 };
		static constexpr value_type		sum3{ 158571277291 };
		static constexpr value_type		sum4{ 361156708538059 };
		static constexpr value_type		moment0{ 1 };
		static constexpr value_type		moment1{ 2151.666666666667 };
		static constexpr value_type		moment2{ 4724226.866666666 };
		static constexpr value_type		moment3{ 10571418486.06667 };
		static constexpr value_type		moment4{ 24077113902537.27 };
		static constexpr value_type		moment5{ 55737883380295736 };
		static constexpr value_type		cmoment0{ 1 };
		static constexpr value_type		cmoment1{ 1.51582450295488e-13 };
		static constexpr value_type		cmoment2{ 94557.42222222222 };
		static constexpr value_type		cmoment3{ -455095.6740740307 };
		static constexpr value_type		cmoment4{ 20573944037.0074 };
		static constexpr value_type		cmoment5{ -208552817972.8403 };
		static constexpr value_type		mean{ 2151.666666666667 };
		static constexpr value_type		population_std_dev{ 307.5019060464865 };
		static constexpr value_type		sample_std_dev{ 318.2947121922131 };
		static constexpr value_type		population_variance{ 94557.42222222222 };
		static constexpr value_type		sample_variance{ 101311.5238095238 };
		static constexpr value_type		coeff_of_sample_var{ 47.08513887351997 };
		static constexpr value_type		population_skewness{ -0.01565161912723 };
		static constexpr value_type		sample_skewness{ -0.01744719303542728 };
		static constexpr value_type		skewness_g1{ -0.01565161912723 };
		static constexpr value_type		skewness_G1{ -0.01744719303542728 };
		static constexpr value_type		skewness_b1{ -0.01411284058865673 };
		static constexpr value_type		sample_kurtosis_pearson{ 3.304073698210441 };
		static constexpr value_type		sample_kurtosis_fisherK{ -1.022849378712635 };
		static constexpr value_type		sample_kurtosis_fisherM{ 2.169542119704933 };
		static constexpr value_type		population_kurtosis_pearson{ 2.301051325539414 };
		static constexpr value_type		population_kurtosis_fisher{ -0.6989486744605857 };
		static constexpr value_type		kurtosis_G2{ -0.4651570710203282 };
		static constexpr value_type		kurtosis_b2{ -0.9955286230856655 };

		// Order:
		static constexpr value_type		minimum{ 1571 };
		static constexpr value_type		quartile1{ 1932 };
		static constexpr value_type		median{ 2165 };
		static constexpr value_type		quartile3{ 2343 };
		static constexpr value_type		maximum{ 2727 };
		static constexpr value_type		mad{ 256 };
		static constexpr value_type		L1{ 2151.666666666667 };
		static constexpr value_type		L2{ 187.0952380952382 };
		static constexpr value_type		L3{ -1.247619047619111 };
		static constexpr value_type		L4{ 22.01465201465203 };
		static constexpr value_type		L5{ 1.516483516483476 };
		static constexpr value_type		L9{ 19.15457875457906 };
		static constexpr value_type		L2_ratio{ 0.0869536350558814 };
		static constexpr value_type		L3_ratio{ -0.006668363451260198 };
		static constexpr value_type		L4_ratio{ 0.1176654854435461 };
		static constexpr value_type		TL1{ 2151.666666666667 };
		static constexpr value_type		TL2{ 187.0952380952382 };
		static constexpr value_type		TL3{ -1.247619047619111 };
		static constexpr value_type		TL4{ 22.01465201465203 };
		static constexpr value_type		TL5{ 1.516483516483476 };
		static constexpr value_type		TL9{ 19.15457875457906 };
		static constexpr value_type		TL1_1{ 2152.914285714286 };
		static constexpr value_type		TL2_1{ 99.04835164835167 };
		static constexpr value_type		TL3_1{ -1.316239316239327 };
		static constexpr value_type		TL4_1{ 8.36288711288713 };
		static constexpr value_type		TL5_1{ 2.668251748251781 };
		static constexpr value_type		TL9_1{ 1.078958078955467 };
		static constexpr value_type		TL1_3_5{ 2071.483916083916 };
		static constexpr value_type		TL2_3_5{ 44.36363636363641 };
		static constexpr value_type		TL3_3_5{ -7.566300366300482 };
		static constexpr value_type		TL4_3_5{ 2.44285714285733 };
		static constexpr value_type		TL5_3_5{ 11.2876190476174 };
		static constexpr value_type		TL2_3_5_ratio{ 0.02141635569515048 };
		static constexpr value_type		TL3_3_5_ratio{ -0.170551852519068 };
		static constexpr value_type		TL4_3_5_ratio{ 0.05506440281030861 };
	};	// struct Correct
}		// namespace pax::metrics
